### ISSUE TITLE
TF error in rviz

### ISSUE THREAD

**Issue by youweicao** [anujjain-dev/unitree-go2-ros2#3]
Hi,
Maybe I met a TF error when using both gazebo and rviz. It seems like this:
![image](https://github.com/user-attachments/assets/44ba391c-f307-4a01-a55f-c80bf35bfbb5)
In fact, probably because of the ubuntu, the program is not running stably. But still thanks to the author.
If someone points out the problems with rviz, that would be great!

**Comment by anujjain-dev** [comment]
Hi @deeprail ,
May I know what is the Ubuntu and Ros version you are using? Also, have you tried installing the ros2 controllers?

**Comment by youweicao** [comment]
Thanks for your attention. I have found the problem.
After trying different situation, I found that:
1. Using unitree_ros2/setup_local.sh, which appoint “lo” as the network card, will cause this problem, as following
![Screenshot from 2024-11-16 20-24-56](https://github.com/user-attachments/assets/8254f6c2-f5a5-4377-ad8a-44a2bfad3cbb)
2. Using unitree_ros2/setup_default.sh, which does not appoint network card, the program goes well. as following
![Screenshot from 2024-11-16 20-29-13](https://github.com/user-attachments/assets/df9f7592-4a09-4c84-9936-853bc5798ea5)

Maybe the problem is caused by DDS middle ware, some communication problems.

Finally, thank you again for your excellent coding skills!

**Comment by youweicao** [comment]
By the way, loopback does not support multicasting

**Comment by anujjain-dev** [comment]
Yes, @deeprail 
Selection of proper middle ware is crucial to execute your ROS 2 processes. If you are not connected to the robot, can use default setup script. While if you want a local network interface, should use the local setup script to source your ROS 2 packages.

Closing this issue assuming there are no further queries related to TF error in rviz.
